---
- name: RedHat - Import Elasticsearch PGP key
  ansible.builtin.rpm_key:
    state: present
    key: "{{es_repo_base}}/GPG-KEY-elasticsearch"

- name: RedHat - Install Elastic App-search from url
  become: yes
  yum: name={% if es_custom_package_url is defined %}{{ es_custom_package_url }}{% else %}{{ es_package_url }}-{{ es_version }}.rpm{% endif %} state=present
  when: not es_use_repository
  register: elastic_app_search_install_from_package
  notify: restart enterprise-search
