---

- name: Include specific Elasticsearch
  include: elastic-app-search-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Elasticsearch
  include: elastic-app-search-RedHat.yml
  when: ansible_os_family == 'RedHat'
