---
- name: Copy Configuration File
  become: yes
  template:
    src: enterprise-search.yml.j2
    dest: "{{ es_conf_dir }}/enterprise-search.yml"
    owner: root
    group: "{{ es_group }}"
    mode: "660"
    force: yes
  register: system_change
  notify: restart enterprise-search

