---
# tasks file for elastic-app-search
- name: include elastic-app-search.yml
  include: elastic-ent-search.yml
  tags:
    - install

- name: include elastic-app-search-config.yml
  include: elastic-ent-search-config.yml
  tags:
    - config

- name: include elastic-app-search-ssl.yml
  include: elastic-ent-search-ssl.yml
  when: es_ssl_enabled
  tags:
    - config
