---
# handlers file for elastic-app-search
- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: true

# Restart service and ensure it is enabled

- name: restart enterprise-search
  become: yes
  service: name=enterprise-search state=restarted enabled=yes
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted
